= Updating the bootloader

== bootupd

The bootloader update is now performed automatically by default. The https://github.com/coreos/bootupd/[bootupd]
project is included in Fedora CoreOS and supports both manual and automatic updates.

This is usually only relevant on bare metal scenarios, or virtualized
hypervisors that support Secure Boot. An example reason to update the
bootloader is for https://eclypsium.com/2020/07/29/theres-a-hole-in-the-boot/[the BootHole vulnerability].

Both the EFI system partition and BIOS MBR can be updated by bootupd.

Inspect the system status:

[source,bash]
----
# bootupctl status
Component EFI
  Installed: grub2-efi-x64-1:2.04-31.fc33.x86_64,shim-x64-15-8.x86_64
  Update: At latest version
----

If an update is available, use `bootupctl update` to apply it manually;
the change will take effect for the next reboot.

[source,bash]
----
# bootupctl update
...
Updated: grub2-efi-x64-1:2.04-31.fc33.x86_64,shim-x64-15-8.x86_64
----

=== Using images that predate bootupd

Older CoreOS images that predate the existence of bootupd need
an explicit "adoption" phase. If `bootupctl status` says the component
is `Adoptable`, perform the adoption with `bootupctl adopt-and-update`.

[source,bash]
----
# bootupctl adopt-and-update
...
Updated: grub2-efi-x64-1:2.04-31.fc33.x86_64,shim-x64-15-8.x86_64
----
