:experimental:
= Fedora CoreOS - Getting Started

Fedora CoreOS (FCOS) has no install-time configuration. Every FCOS system begins with a generic disk image. For each deployment mechanism (cloud VM, local VM, bare metal), configuration can be supplied at first boot. FCOS reads and applies the configuration file with https://github.com/coreos/ignition[Ignition]. For cloud deployments, Ignition gathers the configuration via the cloud’s user-data mechanism. In the case of bare metal, Ignition injects the configuration at install time.

NOTE: For more information on configuration, refer to the documentation for xref:producing-ign.adoc[Producing an Ignition File].

== Launching FCOS

=== Launching in a cloud

Follow the corresponding guide for xref:provisioning-aws.adoc[Amazon Web Services], xref:provisioning-azure.adoc[Azure], or xref:provisioning-digitalocean.adoc[DigitalOcean] to launch an instance of Fedora CoreOS.

=== Launching in a virtual machine hypervisor

Follow the corresponding guide for xref:provisioning-qemu.adoc[QEMU or libvirt] or xref:provisioning-vmware.adoc[VMware] to launch an instance of Fedora CoreOS.

== Installing on bare metal

Follow the xref:bare-metal.adoc[bare metal installation instructions] to install Fedora CoreOS to disk. This procedure injects the specified Ignition configuration at install time.

== Where to report bugs and ask questions

Report bugs to the https://github.com/coreos/fedora-coreos-tracker[Fedora CoreOS Tracker] and ask questions on the `#fedora-coreos` IRC channel on freenode, the https://discussion.fedoraproject.org/c/server/coreos/[Fedora CoreOS forum], or the https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/[mailing list].
