= Manual Rollbacks

When an update is complete, the previous OS deployment remains on disk. If an update causes issues, you can use it as a fallback. This is a manual operation that requires human intervention and console access.

== Temporary rollback

To temporarily boot the previous OS deployment, hold down `Shift` during the OS boot process. When the bootloader menu appears, select the relevant OS entry in the menu.

== Permanent rollback

To permanently revert to the previous OS deployment, log into the target node and run the following commands:

[source,bash]
----
# Stop the service that performs automatic updates
sudo systemctl stop zincati.service

# Mark the previous OS deployment as the default, and immediately reboots into it
sudo rpm-ostree rollback -r
----

Please note that Zincati will keep looking for updates and upgrade to any new available OS deployment, other than the one you just reverted.

If you prefer to temporarily disable auto-updates and manually re-align to the release stream later on, you can perform the following steps:

[source,bash]
----
# Disable Zincati in order to opt-out from future auto-updates
sudo systemctl disable --now zincati.service

[...]

# At a later point, re-align to the tip of stream and immediately reboot into it
ARCH="$(arch)"
STREAM="<YOUR_STREAM>"
sudo rpm-ostree rebase -r "fedora/${ARCH}/coreos/${STREAM}"

# Re-enable auto-updates
sudo systemctl enable --now zincati.service
----
