= Provisioning Fedora CoreOS on QEMU/libvirt

This guide shows how to provision new Fedora CoreOS (FCOS) nodes using QEMU or libvirt.

== Prerequisites

Before provisioning a FCOS machine, you must have an Ignition configuration file containing your customizations. If you do not have one, see xref:producing-ign.adoc[Producing an Ignition File].

== Launching with QEMU or libvirt

. https://getfedora.org/coreos/download/[Download and verify] the latest image suitable for QEMU.

. Uncompress the file. Assuming that the downloaded file is called `fedora-coreos-qemu.qcow2.xz`, the command would be the following:
+
[source, bash]
----
unxz fedora-coreos-qemu.qcow2.xz
----
+
TIP: Make sure that your user has access to `/dev/kvm` (this should already be the case on modern distros), or if `/dev/kvm` is owned by the `kvm` group, adding yourself to that group with `usermod -aG kvm $USER`.

. Launch the VM using `qemu-kvm` or `virt-install`. The Ignition file is passed to the VM via the `-fw_cfg` parameter, which sets the `opt/com.coreos/config` key in the QEMU firmware configuration device. For libvirt, you must pass this through the `--qemu-commandline` argument. You can use `-snapshot` to make `qemu-kvm` allocate temporary storage for the VM, or `qemu-img create` to first create a layered qcow2.
+
.Example launching FCOS with QEMU (temporary storage)
[source, bash]
----
qemu-kvm -m 2048 -cpu host -nographic -snapshot \
	-drive if=virtio,file=fedora-coreos-qemu.qcow2 \
	-fw_cfg name=opt/com.coreos/config,file=path/to/example.ign
----
+
.Example launching FCOS with QEMU (persistent storage)
[source, bash]
----
qemu-img create -f qcow2 -b fedora-coreos-qemu.qcow2 my-fcos-vm.qcow2
qemu-kvm -m 2048 -cpu host -nographic \
	-drive if=virtio,file=my-fcos-vm.qcow2 \
	-fw_cfg name=opt/com.coreos/config,file=path/to/example.ign
----
+
.Example launching FCOS with virt-install
[source, bash]
----
virt-install --connect qemu:///system -n fcos -r 2048 --os-variant=fedora31 --import \
	--graphics=none --disk size=10,backing_store=/path/to/fedora-coreos-qemu.qcow2 \
	--qemu-commandline="-fw_cfg name=opt/com.coreos/config,file=/path/to/example.ign"
----

NOTE: When using `virt-install`, you must specify absolute paths to the image and the Ignition file.

TIP: If running with SELinux enabled, you may need to change the label of the Ignition file to allow access: `chcon -t svirt_home_t path/to/example.ign`

Once the VM has finished booting, its IP addresses will appear on the serial console. You can then SSH into the FCOS VM as the `core` user:

[source, bash]
----
ssh core@<ip address>
----
