# Automatically modified by update-versions.py; comments will not be preserved

site:
  title: Local Preview
  start_page: fedora-coreos::index.adoc
content:
  sources:
  - url: .
    branches: HEAD
ui:
  bundle:
    url: https://asamalik.fedorapeople.org/ui-bundle.zip
    snapshot: true
  default_layout: with_menu
output:
  clean: true
  dir: ./public
  destinations:
  - provider: archive
runtime:
  fetch: true
  cache_dir: ./cache
asciidoc:
  attributes:
    stable-version: 35.20220227.3.0
    ignition-version: 2.13.0
    butane-version: 0.14.0
    coreos-installer-version: 0.13.1
