---
name: Checks

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  butane:
    name: Validate Butane configs
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Print Podman version
        run: dpkg -s podman
      - name: Trivial Podman run
        run: sudo podman run -i --rm quay.io/coreos/butane --version
      - name: Run validator
        run: ./check.py -v
