---
name: Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  butane:
    name: Validate Butane configs
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Run validator
        run: ./check.py -v
