---
name: Checks

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  butane:
    name: Validate Butane configs
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install FUSE
        run: |
          sudo apt-get install fuse-overlayfs
          mkdir -vp ~/.config/containers
          printf "[storage.options]\nmount_program=\"/usr/bin/fuse-overlayfs\"" > ~/.config/containers/storage.conf
      - name: Run validator
        run: ./check.py -v
