---
name: Checks

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  fcc:
    name: Validate FCCs
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Run validator
        run: ./check.py -v
